### ISSUE TITLE
How to sort by different criteria?

### ISSUE THREAD

**Issue by cpartl** [Caleydo/org.caleydo.view.contour#2]
It might be useful to allow the user to sort a column by different criteria (e.g. alphabetically, number of mapped elements, item attributes etc). Also, there might also be a chain of criteria to check (e.g. primary: selected vs. non-selected, secondary: number of mapped elements etc) How should the user be able to do that? How should the interface look like? There is not much space in column headers to accomodate many widgets, so some pop-up, extra view or similar will probably be required. It would also be good to indicate by what a column is currently sorted.

**Comment by alexsb** [comment]
Right now I feel like we should have one multi-tier sort behavior: 
1. Selection (direct or indirect) - Selected Elements on Top. Mouse over does not re-sort.
2. Over-representation - The more incoming relationships an entity has, the higher up it is. This should not be a count but normalized to the size of contained entities (for pathways and clusters of varying size). 
3. Alphabetical (for ties with respect to the other criteria). 

All these criteria should be implemented nested, i.e., within a set of elements matching 1, rules 2 and 3 should also be applied. Within 2, 3 should be applied. 

I would use other parameters, like item attributes for filters, not f or sorting?

**Comment by alexsb** [comment]
We should also consider data driven sorting, e.g., filter by average activity.
