### ISSUE TITLE
In-pathway compound encoding. 

### ISSUE THREAD

**Issue by alexsb** [Caleydo/org.caleydo.view.contour#25]
The following sketches show a proposal for the compound cluster on pathway encoding:

![pathway_compound](https://f.cloud.github.com/assets/2039375/2259084/3e747c4e-9e31-11e3-93f3-ec103ebe8a34.jpg)
![compound_cluster_detail](https://f.cloud.github.com/assets/2039375/2259086/4970a05a-9e31-11e3-9d54-6cb9c1f147f9.jpg)

The bars on the sides of the pathways represent compound clusters, showing only the compounds that are mapped within the pathway. The length of the bars encodes how many compounds within the cluster are mapped. The lines next to the bar indicate how many of them map to how many genes - compounds that map to many genes are associated with the distant lines.

**Comment by alexsb** [comment]
Additional considerations: 
- instead of absolute size of the cluster, we should consider the ratio of the elements of the cluster as the primary visual encoding (i.e., the length)
- the clusters should be based on the filtered set primarily, but should be switchable to the whole set

@wassermai - correct?

**Comment by wassermai** [comment]
correct
