### ISSUE TITLE
Enable filtering based on attribute values

### ISSUE THREAD

**Issue by alexsb** [Caleydo/org.caleydo.view.contour#30]
Specifically, we would like to express data driven filters. E.g., we might want to say "Only show activities that inhibit". Or "only show fingerprints that have a value larger than 5 for attribute C".

**Comment by cpartl** [comment]
The filtering basically works now, but the representation needs to be reworked.
- Scalability: Lots of attribute values cause huge dialogs; Possible solution: show list of all attributes and show them one by one upon selection
- Improve visual representation of valid range for numerical values
