### ISSUE TITLE
Summary representation of activities 

### ISSUE THREAD

**Issue by alexsb** [Caleydo/org.caleydo.view.contour#36]
Anne mentioned that the summary representation of the activity, which shows how many activites there are, is misleading. We decied to use an alternative representation that shows the concentration. Here are two alternative designs:

![2014-03-04 14 11 30](https://f.cloud.github.com/assets/2039375/2325140/57d5574e-a3d1-11e3-9c4e-ef1acc06b23f.jpg)

The first one draws a line whenever there is an activity with the given value, the second one a jittered dot. Both alternatives should use some transparency to deal with overplotting. 

We could consider showing the within-filter elements in color, the others in gray, or we could ignore the filtered ones. @wassermai - do you have an opinion?

**Comment by wassermai** [comment]
I would leave the decision between dots and lines to you. Both contain the same information so I think it is a question of taste or better clarity and I think you are the better judges for both. 
Regarding the filtered elements: it's nice to have them (because they actually contain information, seeing that a compound has been tested against a target and that it was not potent is different from assuming inactivity) but I would not include it if it comes at a big cost in terms of readability.

**Comment by cpartl** [comment]
![activity1](https://f.cloud.github.com/assets/4134949/2347802/97ea3f2c-a550-11e3-955a-2c86bb55a337.png)
![activity2](https://f.cloud.github.com/assets/4134949/2347803/97ed1a80-a550-11e3-804c-99c99b39b22f.png)
The two alternatives for rendering  summary activity ic50 values: The above lines/box shows all values, whereas the below one shows the filtered activities. 

There is a little performance issue with the box plots though, thought it would have to do with calculating the statistics, but it appears to be the rendering itself (or something else).

**Comment by cpartl** [comment]
RFC ;-)

**Comment by alexsb** [comment]
I like both. I feel the line variant is a little more direct in communicating the data. One thing I worry: how do you know that the upper one is the one showing all and the lower one shows only the current activities? 

@wassermai - what do you think?

**Comment by alexsb** [comment]
Is there jitter in the line variant?

**Comment by cpartl** [comment]
This jitter is probably caused by some rounding inconsistencies. I could add a tooltip or a label next to them.

**Comment by cpartl** [comment]
we agreed on box plots
