### ISSUE TITLE
Rename reduce, replace and add

### ISSUE THREAD

**Issue by alexsb** [Caleydo/org.caleydo.view.contour#37]
Current  favorites: 
- Filter current set by relationships for $GENE
- Replace current set by relationships for this $GENE 
- Add all relationships for $GENE

**Comment by cpartl** [comment]
As multiple items can be selected, the above version does not really scale. 
-> Renamed them more generically to:
- Replace current Set by Relationships for selected $ColumnName
- Filter current Set by Relationships for selected  $ColumnName
- Add all Relationships for selected $ColumnName
