### ISSUE TITLE
Introduce derived measures for fingerprints and clusters

### ISSUE THREAD

**Issue by alexsb** [Caleydo/org.caleydo.view.contour#38]
We want to measure, visualize and sort by two measures for fingerprints respectively clusters: 

For individual fingerprints:
- eventfulness - how much does the fingerprint deviate from the baseline (all 0s). This could be simply a sum of all absolute values

For clusters:
- eventfulness of the average
- consistency - how consistent are the elements in the cluster. This could be a sum of the standard deviations of each axes, divided by the number of elements in the cluster (to account for cluster size)

We should visualize these values, both for the fingerprints and the clusters, and have our default ranking on them. 

@wassermai - does that reflect what we discussed?

**Comment by wassermai** [comment]
yes, that's what we discussed. As I said, I can ask Felix whether he has preferred measures that he would like to share.
