### ISSUE TITLE
Gene cluster encoding

### ISSUE THREAD

**Issue by alexsb** [Caleydo/org.caleydo.view.contour#40]
FInd a visualization solution for on-node encoding that communicates:
- how many different clusters map onto the node
- how many compounds map onto the node

@wassermai  - are both equally important, i.e., do we want to encode both? Or is the number of clusters more important?

**Comment by wassermai** [comment]
As discussed before, both is important. As long as it is possible to get quickly from one question to the other, either is fine in the display. For example, would it be possible to
display the number of compounds OR clusters below the node but when I click on the gene, all clusters with compounds (that are arranged at left or right side) are highlighted and the number of compounds per cluster is somehow indicated? Or does this correspond to the ratio sorting that we discussed before? Or do you think that this information is straightforward to infer from the column view below the pathway map if this is limited to the gene of interest?

**Comment by alexsb** [comment]
![image](https://f.cloud.github.com/assets/2039375/2440459/dd0f6b08-ae07-11e3-8466-f58b68092ce8.png)

Yellow: no mapping. Violet to gray: lots to few mapping compounds

RFC

**Comment by alexsb** [comment]
I think this is good enough for now. Closing.
